---

configure:

  update: yes
  reboot: yes
  
  packages: wget curl sudo tree htop vim-nox git
  
  host:
    timezone: America/Chicago
    ntp_servers:
      - 0.us.pool.ntp.org
      - 1.us.pool.ntp.org
  
  environment:
    zsh_shell: yes
    oh_my_zsh: yes
    motd: yes